[package]
name = "ruble"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
printpdf = "0.7"
roxmltree = "0.20"
walkdir = "2.5"
